/**
 * Pluggable AI provider client supporting Google Gemini, Anthropic Claude, and OpenAI.
 * Uses Node.js built-in https module — zero external dependencies.
 * API keys are read from environment variables only.
 */

var https = require('https');
var fs = require('fs');
var path = require('path');
var { RateLimiter } = require('./ai_rate_limiter');

var REPO_ROOT = path.resolve(__dirname, '../../..');
var PROVIDERS_PATH = path.join(REPO_ROOT, 'config/ai/providers.json');

function loadProviders() {
  if (!fs.existsSync(PROVIDERS_PATH)) return { providers: {}, defaultProvider: {} };
  return JSON.parse(fs.readFileSync(PROVIDERS_PATH, 'utf8'));
}

// ---- HTTP helper ----

function httpsRequest(url, options, body) {
  return new Promise(function (resolve, reject) {
    var parsed = new URL(url);
    var reqOpts = {
      hostname: parsed.hostname,
      port: parsed.port || 443,
      path: parsed.pathname + parsed.search,
      method: options.method || 'POST',
      headers: options.headers || {}
    };
    var req = https.request(reqOpts, function (res) {
      var chunks = [];
      res.on('data', function (chunk) { chunks.push(chunk); });
      res.on('end', function () {
        var data = Buffer.concat(chunks).toString('utf8');
        if (res.statusCode >= 200 && res.statusCode < 300) {
          resolve({ status: res.statusCode, body: data });
        } else {
          reject(new Error('HTTP ' + res.statusCode + ': ' + data.substring(0, 500)));
        }
      });
    });
    req.on('error', reject);
    if (body) req.write(body);
    req.end();
  });
}

// ---- Retry wrapper ----

function withRetry(fn, retryConfig) {
  var maxRetries = (retryConfig && retryConfig.maxRetries) || 3;
  var backoffMs = (retryConfig && retryConfig.backoffMs) || 1000;
  var multiplier = (retryConfig && retryConfig.backoffMultiplier) || 2;

  return (function attempt(n) {
    return fn().catch(function (err) {
      if (n >= maxRetries) throw err;
      var delay = backoffMs * Math.pow(multiplier, n);
      return new Promise(function (r) { setTimeout(r, delay); }).then(function () {
        return attempt(n + 1);
      });
    });
  })(0);
}

// ---- Provider-specific implementations ----

function callGoogleGeminiText(apiKey, baseUrl, model, options) {
  var url = baseUrl + '/models/' + model + ':generateContent?key=' + apiKey;
  var genConfig = { temperature: options.temperature || 0.7 };
  if (options.maxTokens) genConfig.maxOutputTokens = options.maxTokens;
  if (options.responseFormat === 'json') genConfig.responseMimeType = 'application/json';

  var body = JSON.stringify({
    contents: [{ parts: [{ text: options.prompt }] }],
    generationConfig: genConfig
  });

  return httpsRequest(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' }
  }, body).then(function (res) {
    var data = JSON.parse(res.body);
    var text = '';
    if (data.candidates && data.candidates[0] && data.candidates[0].content) {
      var parts = data.candidates[0].content.parts;
      text = parts.map(function (p) { return p.text || ''; }).join('');
    }
    var usage = data.usageMetadata || {};
    return {
      text: text,
      usage: {
        promptTokens: usage.promptTokenCount || 0,
        completionTokens: usage.candidatesTokenCount || 0
      },
      cost: options.costEstimate || 0
    };
  });
}

function callGoogleImagen(apiKey, baseUrl, model, options) {
  var url = baseUrl + '/models/' + model + ':predict?key=' + apiKey;
  var params = {
    sampleCount: 1,
    safetyFilterLevel: options.safetyFilterLevel || 'block_medium_and_above'
  };
  if (options.width && options.height) {
    var w = options.width;
    var h = options.height;
    if (w === h) params.aspectRatio = '1:1';
    else if (w > h) params.aspectRatio = '16:9';
    else params.aspectRatio = '9:16';
  }

  var body = JSON.stringify({
    instances: [{ prompt: options.prompt }],
    parameters: params
  });

  return httpsRequest(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' }
  }, body).then(function (res) {
    var data = JSON.parse(res.body);
    if (!data.predictions || !data.predictions[0]) {
      throw new Error('No image generated by Imagen');
    }
    var base64Data = data.predictions[0].bytesBase64Encoded;
    if (options.outputPath) {
      var dir = path.dirname(options.outputPath);
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(options.outputPath, Buffer.from(base64Data, 'base64'));
    }
    return {
      filePath: options.outputPath || null,
      base64: options.outputPath ? undefined : base64Data,
      cost: options.costEstimate || 0.04
    };
  });
}

function callGoogleGeminiMultimodal(apiKey, baseUrl, model, options) {
  var url = baseUrl + '/models/' + model + ':generateContent?key=' + apiKey;
  var genConfig = { temperature: options.temperature || 0.7 };
  if (options.maxTokens) genConfig.maxOutputTokens = options.maxTokens;
  if (options.responseFormat === 'json') genConfig.responseMimeType = 'application/json';

  // Build parts array: text prompt + inline image data
  var parts = [{ text: options.prompt }];
  if (options.imageBase64 && options.imageMimeType) {
    parts.push({
      inline_data: {
        mime_type: options.imageMimeType,
        data: options.imageBase64
      }
    });
  }

  var body = JSON.stringify({
    contents: [{ parts: parts }],
    generationConfig: genConfig
  });

  return httpsRequest(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' }
  }, body).then(function (res) {
    var data = JSON.parse(res.body);
    var text = '';
    if (data.candidates && data.candidates[0] && data.candidates[0].content) {
      var resParts = data.candidates[0].content.parts;
      text = resParts.map(function (p) { return p.text || ''; }).join('');
    }
    var usage = data.usageMetadata || {};
    return {
      text: text,
      usage: {
        promptTokens: usage.promptTokenCount || 0,
        completionTokens: usage.candidatesTokenCount || 0
      },
      cost: options.costEstimate || 0.002
    };
  });
}

function callAnthropicClaude(apiKey, baseUrl, model, options) {
  var url = baseUrl + '/messages';
  var body = JSON.stringify({
    model: model,
    max_tokens: options.maxTokens || 2000,
    temperature: options.temperature || 0.7,
    messages: [{ role: 'user', content: options.prompt }]
  });

  return httpsRequest(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01'
    }
  }, body).then(function (res) {
    var data = JSON.parse(res.body);
    var text = '';
    if (data.content && data.content[0]) {
      text = data.content[0].text || '';
    }
    var usage = data.usage || {};
    return {
      text: text,
      usage: {
        promptTokens: usage.input_tokens || 0,
        completionTokens: usage.output_tokens || 0
      },
      cost: options.costEstimate || 0
    };
  });
}

function callOpenAIText(apiKey, baseUrl, model, options) {
  var url = baseUrl + '/chat/completions';
  var reqBody = {
    model: model,
    temperature: options.temperature || 0.7,
    max_tokens: options.maxTokens || 2000,
    messages: [{ role: 'user', content: options.prompt }]
  };
  if (options.responseFormat === 'json') {
    reqBody.response_format = { type: 'json_object' };
  }

  return httpsRequest(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer ' + apiKey
    }
  }, JSON.stringify(reqBody)).then(function (res) {
    var data = JSON.parse(res.body);
    var text = '';
    if (data.choices && data.choices[0] && data.choices[0].message) {
      text = data.choices[0].message.content || '';
    }
    var usage = data.usage || {};
    return {
      text: text,
      usage: {
        promptTokens: usage.prompt_tokens || 0,
        completionTokens: usage.completion_tokens || 0
      },
      cost: options.costEstimate || 0
    };
  });
}

function callOpenAIImage(apiKey, baseUrl, model, options) {
  var url = baseUrl + '/images/generations';
  var reqBody = {
    model: model || 'dall-e-3',
    prompt: options.prompt,
    n: 1,
    size: (options.width && options.height)
      ? options.width + 'x' + options.height
      : '1024x1024',
    response_format: 'b64_json'
  };

  return httpsRequest(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer ' + apiKey
    }
  }, JSON.stringify(reqBody)).then(function (res) {
    var data = JSON.parse(res.body);
    if (!data.data || !data.data[0]) throw new Error('No image generated by DALL-E');
    var base64Data = data.data[0].b64_json;
    if (options.outputPath) {
      var dir = path.dirname(options.outputPath);
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(options.outputPath, Buffer.from(base64Data, 'base64'));
    }
    return {
      filePath: options.outputPath || null,
      cost: options.costEstimate || 0.04
    };
  });
}

// ---- Mock provider for dry runs ----

function mockGenerateText(options) {
  return Promise.resolve({
    text: JSON.stringify([
      { text: 'Mock variation 1 of: ' + (options.prompt || '').substring(0, 30), rationale: 'Mock', score: 0.8 },
      { text: 'Mock variation 2', rationale: 'Mock', score: 0.7 }
    ]),
    usage: { promptTokens: 100, completionTokens: 50 },
    cost: options.costEstimate || 0.001
  });
}

function mockGenerateMultimodal(options) {
  return Promise.resolve({
    text: 'MOCK ENHANCED PROMPT: Cinematic slow-motion dolly shot through a sun-drenched studio space, ' +
      'golden hour light streaming through floor-to-ceiling windows. Camera glides past the hero product ' +
      'positioned on a marble pedestal, shallow depth of field creating dreamy bokeh in the background. ' +
      'Anamorphic lens flare catches the rim light. Film grain overlay at 15%. Color grade: warm amber ' +
      'shadows, lifted highlights. 24fps, 4K resolution. Original context: ' +
      (options.prompt || '').substring(0, 50),
    usage: { promptTokens: 200, completionTokens: 150 },
    cost: options.costEstimate || 0.002
  });
}

function mockGenerateImage(options) {
  if (options.outputPath) {
    var dir = path.dirname(options.outputPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    // Write a minimal 1x1 PNG placeholder
    var pngHeader = Buffer.from([
      0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A,
      0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52,
      0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
      0x08, 0x02, 0x00, 0x00, 0x00, 0x90, 0x77, 0x53,
      0xDE, 0x00, 0x00, 0x00, 0x0C, 0x49, 0x44, 0x41,
      0x54, 0x08, 0xD7, 0x63, 0xF8, 0xCF, 0xC0, 0x00,
      0x00, 0x00, 0x02, 0x00, 0x01, 0xE2, 0x21, 0xBC,
      0x33, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E,
      0x44, 0xAE, 0x42, 0x60, 0x82
    ]);
    fs.writeFileSync(options.outputPath, pngHeader);
  }
  return Promise.resolve({
    filePath: options.outputPath || null,
    cost: options.costEstimate || 0.04
  });
}

// ---- AIClient class ----

/**
 * @param {string} providerName - 'google_gemini' | 'anthropic_claude' | 'openai'
 * @param {Object} [overrideConfig] - Override provider config fields
 */
function AIClient(providerName, overrideConfig) {
  var providersConfig = loadProviders();
  var provider = providersConfig.providers[providerName];
  if (!provider) throw new Error('Unknown AI provider: ' + providerName);

  this.providerName = providerName;
  this.config = Object.assign({}, provider, overrideConfig || {});
  this.apiKey = process.env[this.config.apiKeyEnvVar] || null;
  this.dryRun = !this.apiKey;
  this.rateLimiter = new RateLimiter(
    this.config.rateLimits ? this.config.rateLimits.requestsPerMinute : 60
  );
}

/**
 * Generate text completion.
 * @param {Object} options
 * @param {string} options.prompt
 * @param {string} [options.model]
 * @param {number} [options.temperature]
 * @param {number} [options.maxTokens]
 * @param {string} [options.responseFormat] - 'json' | 'text'
 * @param {number} [options.costEstimate]
 * @returns {Promise<{ text: string, usage: Object, cost: number }>}
 */
AIClient.prototype.generateText = function (options) {
  var self = this;
  if (self.dryRun) return mockGenerateText(options);

  var model = options.model || (self.config.models && self.config.models.text);
  var apiKey = self.apiKey;
  var baseUrl = self.config.baseUrl;
  var retryConfig = self.config.retryConfig;

  return self.rateLimiter.acquire().then(function () {
    var callFn;
    if (self.providerName === 'google_gemini') {
      callFn = function () { return callGoogleGeminiText(apiKey, baseUrl, model, options); };
    } else if (self.providerName === 'anthropic_claude') {
      callFn = function () { return callAnthropicClaude(apiKey, baseUrl, model, options); };
    } else if (self.providerName === 'openai') {
      callFn = function () { return callOpenAIText(apiKey, baseUrl, model, options); };
    } else {
      return Promise.reject(new Error('Unsupported provider for text: ' + self.providerName));
    }
    return withRetry(callFn, retryConfig);
  });
};

/**
 * Generate an image.
 * @param {Object} options
 * @param {string} options.prompt
 * @param {string} [options.model]
 * @param {number} [options.width]
 * @param {number} [options.height]
 * @param {string} [options.negativePrompt]
 * @param {string} [options.outputPath]
 * @param {string} [options.safetyFilterLevel]
 * @param {number} [options.costEstimate]
 * @returns {Promise<{ filePath: string, cost: number }>}
 */
AIClient.prototype.generateImage = function (options) {
  var self = this;
  if (self.dryRun) return mockGenerateImage(options);

  var model = options.model || (self.config.models && self.config.models.image);
  var apiKey = self.apiKey;
  var baseUrl = self.config.baseUrl;
  var retryConfig = self.config.retryConfig;

  return self.rateLimiter.acquire().then(function () {
    var callFn;
    if (self.providerName === 'google_gemini') {
      callFn = function () { return callGoogleImagen(apiKey, baseUrl, model, options); };
    } else if (self.providerName === 'openai') {
      callFn = function () { return callOpenAIImage(apiKey, baseUrl, model, options); };
    } else {
      return Promise.reject(new Error('Unsupported provider for images: ' + self.providerName));
    }
    return withRetry(callFn, retryConfig);
  });
};

/**
 * Generate text from a multimodal input (text + image).
 * Sends the image inline to the model for visual analysis.
 * @param {Object} options
 * @param {string} options.prompt - Text prompt
 * @param {string} options.imagePath - Path to the image file to analyze
 * @param {string} [options.model]
 * @param {number} [options.temperature]
 * @param {number} [options.maxTokens]
 * @param {string} [options.responseFormat] - 'json' | 'text'
 * @param {number} [options.costEstimate]
 * @returns {Promise<{ text: string, usage: Object, cost: number }>}
 */
AIClient.prototype.generateMultimodal = function (options) {
  var self = this;
  if (self.dryRun) return mockGenerateMultimodal(options);

  var model = options.model || (self.config.models && self.config.models.multimodal) || (self.config.models && self.config.models.text);
  var apiKey = self.apiKey;
  var baseUrl = self.config.baseUrl;
  var retryConfig = self.config.retryConfig;

  // Read image and convert to base64
  var imageBase64 = null;
  var imageMimeType = 'image/png';
  if (options.imagePath && fs.existsSync(options.imagePath)) {
    imageBase64 = fs.readFileSync(options.imagePath).toString('base64');
    var ext = path.extname(options.imagePath).toLowerCase();
    if (ext === '.jpg' || ext === '.jpeg') imageMimeType = 'image/jpeg';
    else if (ext === '.webp') imageMimeType = 'image/webp';
    else if (ext === '.gif') imageMimeType = 'image/gif';
  }

  return self.rateLimiter.acquire().then(function () {
    if (self.providerName === 'google_gemini') {
      var callFn = function () {
        return callGoogleGeminiMultimodal(apiKey, baseUrl, model, {
          prompt: options.prompt,
          imageBase64: imageBase64,
          imageMimeType: imageMimeType,
          temperature: options.temperature,
          maxTokens: options.maxTokens,
          responseFormat: options.responseFormat,
          costEstimate: options.costEstimate
        });
      };
      return withRetry(callFn, retryConfig);
    }
    // Fallback: text-only for providers without multimodal
    return self.generateText(options);
  });
};

/**
 * Check if client is in dry-run mode (no API key set).
 * @returns {boolean}
 */
AIClient.prototype.isDryRun = function () {
  return this.dryRun;
};

module.exports = { AIClient: AIClient };
